spring: 
    datasource:
        url: jdbc:h2:./devdb
        username: fatihbaba98
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update 
        properties:
            javax:
                persistence:
                    validation:
                        mode: none

